blank_issues_enabled: true
contact_links:
  - name: Azlora Core Security Policy
    url: https://github.com/azlora/azlora/blob/master/SECURITY.md
    about: View security policy
  - name: Azlora Core Developers
    url: https://bitcoincore.org
    about: Azlora Core homepage
